AllCops:
  Exclude:
    - '**/dcell.gemspec'
    - '**/Gemfile'
    - '**/Rakefile'
    - 'benchmarks/*'
    - 'tasks/*'
    - 'examples/*'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/LiteralInCondition:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/AndOr:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/EachWithObject:
  Enabled: true

Style/InfiniteLoop:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Metrics/LineLength:
  Max: 120

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/AccessModifierIndentation:
  Enabled: false

Style/TrailingComma:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space

Style/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Style/EmptyLinesAroundAccessModifier:
  Enabled: false
