language: ruby

before_install:
  - ./travis/deps.sh

before_script:
  - ./travis/prep.sh

services:
  - redis-server
  - cassandra

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby
  - jruby-9.0.5.0
  - rbx-2

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: jruby-9.0.5.0
    - rvm: rbx-2
    - env: DCELL_TEST_ADAPTER=cassandra
    - env: DCELL_TEST_ADAPTER=zk

branches:
  only:
    - master

env:
    - DCELL_TEST_ADAPTER=redis
    - DCELL_TEST_ADAPTER=cassandra
    - DCELL_TEST_ADAPTER=zk
