before_install: sudo apt-get install libzmq3-dev

services:
  - mongodb
  - redis-server

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-19mode # rbx seems to be losing exception messages o_O

branches:
  only:
    - master

env:
    - DCELL_TEST_ADAPTER=redis
    - DCELL_TEST_ADAPTER=mongodb

matrix:
  exclude:
    - service: mongodb
      env: DCELL_TEST_ADAPTER=redis
    - service: redis
      env: DCELL_TEST_ADAPTER=mongodb
